{
 "title": "Plugin Home",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Buffer Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Metrics" }
   ],
   "targets": [
    {
     "alias": "Writes InfluxDB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "internal_write",
     "select": [
      [
       { "params": [ "buffer_size" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "output", "operator": "=", "value": "influxdb" }
     ]
    }
   ]
  },
  {
   "title": "Buffer Fullness",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "internal_write",
     "query": "SELECT last(\"buffer_size\") / last(\"buffer_limit\")  * 100 FROM \"internal\".\"internal_write\" WHERE (\"output\" = 'influxdb') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "buffer_size" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "buffer_limit" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "output", "operator": "=", "value": "influxdb" }
     ]
    }
   ]
  },
  {
   "title": "Gathered Metrics per Hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Metrics" }
   ],
   "targets": [
    {
     "alias": "Gathered metrics/h",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "internal_gather",
     "select": [
      [
       { "params": [ "metrics_gathered" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1h" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "input", "operator": "=", "value": "http" }
     ]
    }
   ]
  }
 ]
}