#!/bin/bash

# To use important variables from command line use the following code:
COMMAND=$0    # Zero argument is shell command
PTEMPDIR=$1   # First argument is temp folder during install
PSHNAME=$2    # Second argument is Plugin-Name for scipts etc.
PDIR=$3       # Third argument is Plugin installation folder
PVERSION=$4   # Forth argument is Plugin version
#LBHOMEDIR=$5 # Comes from /etc/environment now. Fifth argument is
              # Base folder of LoxBerry
PTEMPPATH=$6  # Sixth argument is full temp path during install (see also $1)

# Combine them with /etc/environment
PCGI=$LBPCGI/$PDIR
PHTML=$LBPHTML/$PDIR
PTEMPL=$LBPTEMPL/$PDIR
PDATA=$LBPDATA/$PDIR
PLOG=$LBPLOG/$PDIR # Note! This is stored on a Ramdisk now!
PCONFIG=$LBPCONFIG/$PDIR
PSBIN=$LBPSBIN/$PDIR
PBIN=$LBPBIN/$PDIR

echo "This is the stats4lox uninstall script."

echo "<INFO> Stopping influxdb, grafana and telegraf services."
systemctl stop influxdb
systemctl stop telegraf
systemctl stop grafana-server

echo "<INFO> Deactivating my own InfluxDB configuration."
if [ -L /etc/influxdb ]; then
	rm /etc/influxdb
	mv /etc/influxdb.orig /etc/influxdb
fi

echo "<INFO> Deactivating my own Telegraf configuration."
if [ -L /etc/telegraf ]; then
	rm /etc/telegraf
	rm /etc/default/telegraf
	mv /etc/telegraf.orig /etc/telegraf
	mv /etc/default/telegraf.orig /etc/default/telegraf
fi

echo "<INFO> Deactivating my own Grafana configuration."
if [ -L /etc/grafana ]; then
	rm /etc/grafana
	mv /etc/grafana.orig /etc/grafana
fi

echo "<INFO> Backing up Stats4Lox databases - just in case you forgot to make a backup..."
rm -r $PDATA\.backup
mv $PDATA $PDATA\.backup
mv $PCONFIG/cred.json $PDATA\.backup

echo "<INFO> Removing sysctl config."
rm -f /etc/sysctl.d/96-stats4lox.conf

echo "<INFO> Removing sytemd config."
# The wildcard covers both the old name (00-stats4lox.conf) and the current
# ones (00-stats4lox-influxdb.conf and friends).
rm -f /etc/systemd/system/influxdb.service.d/00-stats4lox*.conf
rm -f /etc/systemd/system/telegraf.service.d/00-stats4lox*.conf
rm -f /etc/systemd/system/grafana-server.service.d/00-stats4lox*.conf
systemctl daemon-reload

# Leaving our apt configuration behind breaks the package management of the
# whole system - apt-get update then fails for the user as well.
echo "<INFO> Removing apt repositories, pins and keyrings added by Stats4Lox."
rm -f /etc/apt/sources.list.d/influxdata.sources
rm -f /etc/apt/sources.list.d/influxdata.list
rm -f /etc/apt/sources.list.d/influxdb.list
rm -f /etc/apt/sources.list.d/grafana.sources
rm -f /etc/apt/sources.list.d/grafana.list
rm -f /etc/apt/preferences.d/stats4lox-influxdata
rm -f /etc/apt/preferences.d/stats4lox-grafana
rm -f /etc/apt/preferences.d/influxdb
rm -f /etc/apt/preferences.d/telegraf
rm -f /etc/apt/preferences.d/grafana
rm -f /etc/apt/keyrings/influxdata-archive.asc
rm -f /etc/apt/keyrings/grafana.asc
rm -f /usr/share/keyrings/influxdata-archive-keyring.gpg
rm -f /usr/share/keyrings/grafana-archive-keyring.gpg
rm -f /etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg
rm -f /etc/apt/trusted.gpg.d/grafanadata-archive_compat.gpg
APT_LISTCHANGES_FRONTEND=none DEBIAN_FRONTEND=noninteractive apt-get -q -y update || true

echo "<INFO> Disabling influxdb, grafana and telegraf services."
systemctl disable influxdb
systemctl disable telegraf
systemctl disable grafana-server

echo "<INFO> Stopping internal services."
pkill -f mqttlive.php >/dev/null 2>&1
pkill -f import_scheduler.pl > /dev/null 2>&1
pkill -f import_loxone.pl> /dev/null 2>&1

# Clean up old installation
echo "<INFO> Cleaning old temporary files"
S4LTMP=`jq -r '.stats4lox.s4ltmp' $PCONFIG/stats4lox.json`
rm -fr $S4LTMP

echo "<INFO> Removing all plugin files as user root"
rm -rf $PDATA
rm -rf $PCONFIG
rm -rf $PLOG

exit 0
